#!/bin/bash -eu
versions() {
	git tag | grep '^v'
}

if [[ $# > 0 ]]; then
	current="$1"
else
	current="$(versions | tail -n1)"
fi
if [[ $# > 1 ]]; then
	previous="$2"
else
	previous="$(versions | tail -n2 | head -n1)"
fi

echo "Changelog $previous -> $current"
echo "=========================="

git log "${previous}..${current}" --pretty=oneline | cut -d' ' -f2- | sed -E -e 's/^/* /'
