#!/bin/bash -eu
versions() {
	git tag | grep '^v'
}

current="$(versions | tail -n1)"
previous="$(versions | tail -n2 | head -n1)"

echo "Changelog $previous -> $current"
echo "=========================="

git log "${previous}..${current}" --pretty=oneline | cut -d' ' -f2- | sed -E -e 's/^/* /'
