#!/bin/bash -eux
# start the emulator
echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a --sdcard 200M
emulator -avd test -no-audio -no-window &
android-wait-for-emulator
adb shell input keyevent 82 &
