#!/bin/bash -eu
# start the emulator

echo "[start_emulator] Listing available ABIs..."
android list sdk --extended --no-ui --all

echo "[start_emulator] Creating ABI..."
echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a --sdcard 200M

echo "[start_emulator] Starting emulator..."
emulator -avd test -no-audio -no-window &

echo "[start_emulator] Waiting for emulator..."
android-wait-for-emulator

echo "[start_emulator] Pressing a key in the emulator..."
adb shell input keyevent 82 &

echo "[start_emulator] Complete."
