name: cht-gateway build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-XX:MaxPermSize=512m"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: android-actions/setup-android@v2
      - run: yes | sdkmanager 'platforms;android-28'
      - run: openssl aes-256-cbc -K $encrypted_937040266844_key -iv $encrypted_937040266844_iv -in medic-official.keystore.enc -out medic-official.keystore -d
      - run: make travis
