name: cht-gateway build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-XX:MaxPermSize=512m"
  ANDROID_KEY_ALIAS: medicmobile
  ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  ANDROID_KEYSTORE_PATH: ./medic-official.keystore
  ANDROID_SECRETS_KEY: ${{ secrets.ANDROID_SECRETS_KEY }}
  ANDROID_SECRETS_IV: ${{ secrets.ANDROID_SECRETS_IV }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: android-actions/setup-android@v2
      - run: yes | sdkmanager 'platforms;android-28'
      - run: openssl aes-256-cbc -K ${{ secrets.ANDROID_SECRETS_KEY }} -iv ${{ secrets.ANDROID_SECRETS_IV }} -in medic-official.keystore.enc -out medic-official.keystore -d
      - run: make travis
